#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BibliotekaDB")]
	public partial class LINQtoSQLClassDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKsiazka(Ksiazka instance);
    partial void UpdateKsiazka(Ksiazka instance);
    partial void DeleteKsiazka(Ksiazka instance);
    partial void InsertKategoria(Kategoria instance);
    partial void UpdateKategoria(Kategoria instance);
    partial void DeleteKategoria(Kategoria instance);
    partial void InsertAutor(Autor instance);
    partial void UpdateAutor(Autor instance);
    partial void DeleteAutor(Autor instance);
    partial void InsertCzytelnik(Czytelnik instance);
    partial void UpdateCzytelnik(Czytelnik instance);
    partial void DeleteCzytelnik(Czytelnik instance);
    partial void InsertWypozyczenie(Wypozyczenie instance);
    partial void UpdateWypozyczenie(Wypozyczenie instance);
    partial void DeleteWypozyczenie(Wypozyczenie instance);
    #endregion
		
		public LINQtoSQLClassDataContext() : 
				base(global::WpfApp1.Properties.Settings.Default.BibliotekaDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLClassDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLClassDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLClassDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public LINQtoSQLClassDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Ksiazka> Ksiazka
		{
			get
			{
				return this.GetTable<Ksiazka>();
			}
		}
		
		public System.Data.Linq.Table<Kategoria> Kategoria
		{
			get
			{
				return this.GetTable<Kategoria>();
			}
		}
		
		public System.Data.Linq.Table<Autor> Autor
		{
			get
			{
				return this.GetTable<Autor>();
			}
		}
		
		public System.Data.Linq.Table<Czytelnik> Czytelnik
		{
			get
			{
				return this.GetTable<Czytelnik>();
			}
		}
		
		public System.Data.Linq.Table<Wypozyczenie> Wypozyczenie
		{
			get
			{
				return this.GetTable<Wypozyczenie>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ksiazka")]
	public partial class Ksiazka : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_Ksiazka_Id;
		
		private string _Tytul;
		
		private System.Nullable<int> _Fk_Author_Id;
		
		private System.Nullable<int> _Fk_Kategoria_Id;
		
		private string _Wydawnictwo;
		
		private string _Dostepnosc;
		
		private EntitySet<Wypozyczenie> _Wypozyczenie;
		
		private EntityRef<Kategoria> _Kategoria;
		
		private EntityRef<Autor> _Autor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_Ksiazka_IdChanging(int value);
    partial void OnPk_Ksiazka_IdChanged();
    partial void OnTytulChanging(string value);
    partial void OnTytulChanged();
    partial void OnFk_Author_IdChanging(System.Nullable<int> value);
    partial void OnFk_Author_IdChanged();
    partial void OnFk_Kategoria_IdChanging(System.Nullable<int> value);
    partial void OnFk_Kategoria_IdChanged();
    partial void OnWydawnictwoChanging(string value);
    partial void OnWydawnictwoChanged();
    partial void OnDostepnoscChanging(string value);
    partial void OnDostepnoscChanged();
    #endregion
		
		public Ksiazka()
		{
			this._Wypozyczenie = new EntitySet<Wypozyczenie>(new Action<Wypozyczenie>(this.attach_Wypozyczenie), new Action<Wypozyczenie>(this.detach_Wypozyczenie));
			this._Kategoria = default(EntityRef<Kategoria>);
			this._Autor = default(EntityRef<Autor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_Ksiazka_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Pk_Ksiazka_Id
		{
			get
			{
				return this._Pk_Ksiazka_Id;
			}
			set
			{
				if ((this._Pk_Ksiazka_Id != value))
				{
					this.OnPk_Ksiazka_IdChanging(value);
					this.SendPropertyChanging();
					this._Pk_Ksiazka_Id = value;
					this.SendPropertyChanged("Pk_Ksiazka_Id");
					this.OnPk_Ksiazka_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tytul", DbType="VarChar(255)")]
		public string Tytul
		{
			get
			{
				return this._Tytul;
			}
			set
			{
				if ((this._Tytul != value))
				{
					this.OnTytulChanging(value);
					this.SendPropertyChanging();
					this._Tytul = value;
					this.SendPropertyChanged("Tytul");
					this.OnTytulChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_Author_Id", DbType="Int")]
		public System.Nullable<int> Fk_Author_Id
		{
			get
			{
				return this._Fk_Author_Id;
			}
			set
			{
				if ((this._Fk_Author_Id != value))
				{
					if (this._Autor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFk_Author_IdChanging(value);
					this.SendPropertyChanging();
					this._Fk_Author_Id = value;
					this.SendPropertyChanged("Fk_Author_Id");
					this.OnFk_Author_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_Kategoria_Id", DbType="Int")]
		public System.Nullable<int> Fk_Kategoria_Id
		{
			get
			{
				return this._Fk_Kategoria_Id;
			}
			set
			{
				if ((this._Fk_Kategoria_Id != value))
				{
					if (this._Kategoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFk_Kategoria_IdChanging(value);
					this.SendPropertyChanging();
					this._Fk_Kategoria_Id = value;
					this.SendPropertyChanged("Fk_Kategoria_Id");
					this.OnFk_Kategoria_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wydawnictwo", DbType="VarChar(255)")]
		public string Wydawnictwo
		{
			get
			{
				return this._Wydawnictwo;
			}
			set
			{
				if ((this._Wydawnictwo != value))
				{
					this.OnWydawnictwoChanging(value);
					this.SendPropertyChanging();
					this._Wydawnictwo = value;
					this.SendPropertyChanged("Wydawnictwo");
					this.OnWydawnictwoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dostepnosc", DbType="VarChar(255)")]
		public string Dostepnosc
		{
			get
			{
				return this._Dostepnosc;
			}
			set
			{
				if ((this._Dostepnosc != value))
				{
					this.OnDostepnoscChanging(value);
					this.SendPropertyChanging();
					this._Dostepnosc = value;
					this.SendPropertyChanged("Dostepnosc");
					this.OnDostepnoscChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ksiazka_Wypozyczenie", Storage="_Wypozyczenie", ThisKey="Pk_Ksiazka_Id", OtherKey="Fk_Ksiazka_Id")]
		public EntitySet<Wypozyczenie> Wypozyczenie
		{
			get
			{
				return this._Wypozyczenie;
			}
			set
			{
				this._Wypozyczenie.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategoria_Ksiazka", Storage="_Kategoria", ThisKey="Fk_Kategoria_Id", OtherKey="Pk_Kategoria_Id", IsForeignKey=true)]
		public Kategoria Kategoria
		{
			get
			{
				return this._Kategoria.Entity;
			}
			set
			{
				Kategoria previousValue = this._Kategoria.Entity;
				if (((previousValue != value) 
							|| (this._Kategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kategoria.Entity = null;
						previousValue.Ksiazka.Remove(this);
					}
					this._Kategoria.Entity = value;
					if ((value != null))
					{
						value.Ksiazka.Add(this);
						this._Fk_Kategoria_Id = value.Pk_Kategoria_Id;
					}
					else
					{
						this._Fk_Kategoria_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kategoria");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Autor_Ksiazka", Storage="_Autor", ThisKey="Fk_Author_Id", OtherKey="Pk_Autor_Id", IsForeignKey=true)]
		public Autor Autor
		{
			get
			{
				return this._Autor.Entity;
			}
			set
			{
				Autor previousValue = this._Autor.Entity;
				if (((previousValue != value) 
							|| (this._Autor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Autor.Entity = null;
						previousValue.Ksiazka.Remove(this);
					}
					this._Autor.Entity = value;
					if ((value != null))
					{
						value.Ksiazka.Add(this);
						this._Fk_Author_Id = value.Pk_Autor_Id;
					}
					else
					{
						this._Fk_Author_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Autor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Wypozyczenie(Wypozyczenie entity)
		{
			this.SendPropertyChanging();
			entity.Ksiazka = this;
		}
		
		private void detach_Wypozyczenie(Wypozyczenie entity)
		{
			this.SendPropertyChanging();
			entity.Ksiazka = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategoria")]
	public partial class Kategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_Kategoria_Id;
		
		private string _Kategoria1;
		
		private EntitySet<Ksiazka> _Ksiazka;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_Kategoria_IdChanging(int value);
    partial void OnPk_Kategoria_IdChanged();
    partial void OnKategoria1Changing(string value);
    partial void OnKategoria1Changed();
    #endregion
		
		public Kategoria()
		{
			this._Ksiazka = new EntitySet<Ksiazka>(new Action<Ksiazka>(this.attach_Ksiazka), new Action<Ksiazka>(this.detach_Ksiazka));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_Kategoria_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Pk_Kategoria_Id
		{
			get
			{
				return this._Pk_Kategoria_Id;
			}
			set
			{
				if ((this._Pk_Kategoria_Id != value))
				{
					this.OnPk_Kategoria_IdChanging(value);
					this.SendPropertyChanging();
					this._Pk_Kategoria_Id = value;
					this.SendPropertyChanged("Pk_Kategoria_Id");
					this.OnPk_Kategoria_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Kategoria", Storage="_Kategoria1", DbType="VarChar(255)")]
		public string Kategoria1
		{
			get
			{
				return this._Kategoria1;
			}
			set
			{
				if ((this._Kategoria1 != value))
				{
					this.OnKategoria1Changing(value);
					this.SendPropertyChanging();
					this._Kategoria1 = value;
					this.SendPropertyChanged("Kategoria1");
					this.OnKategoria1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategoria_Ksiazka", Storage="_Ksiazka", ThisKey="Pk_Kategoria_Id", OtherKey="Fk_Kategoria_Id")]
		public EntitySet<Ksiazka> Ksiazka
		{
			get
			{
				return this._Ksiazka;
			}
			set
			{
				this._Ksiazka.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ksiazka(Ksiazka entity)
		{
			this.SendPropertyChanging();
			entity.Kategoria = this;
		}
		
		private void detach_Ksiazka(Ksiazka entity)
		{
			this.SendPropertyChanging();
			entity.Kategoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Autor")]
	public partial class Autor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_Autor_Id;
		
		private string _Imie;
		
		private string _Nazwisko;
		
		private EntitySet<Ksiazka> _Ksiazka;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_Autor_IdChanging(int value);
    partial void OnPk_Autor_IdChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNazwiskoChanging(string value);
    partial void OnNazwiskoChanged();
    #endregion
		
		public Autor()
		{
			this._Ksiazka = new EntitySet<Ksiazka>(new Action<Ksiazka>(this.attach_Ksiazka), new Action<Ksiazka>(this.detach_Ksiazka));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_Autor_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Pk_Autor_Id
		{
			get
			{
				return this._Pk_Autor_Id;
			}
			set
			{
				if ((this._Pk_Autor_Id != value))
				{
					this.OnPk_Autor_IdChanging(value);
					this.SendPropertyChanging();
					this._Pk_Autor_Id = value;
					this.SendPropertyChanged("Pk_Autor_Id");
					this.OnPk_Autor_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="VarChar(255)")]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nazwisko", DbType="VarChar(255)")]
		public string Nazwisko
		{
			get
			{
				return this._Nazwisko;
			}
			set
			{
				if ((this._Nazwisko != value))
				{
					this.OnNazwiskoChanging(value);
					this.SendPropertyChanging();
					this._Nazwisko = value;
					this.SendPropertyChanged("Nazwisko");
					this.OnNazwiskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Autor_Ksiazka", Storage="_Ksiazka", ThisKey="Pk_Autor_Id", OtherKey="Fk_Author_Id")]
		public EntitySet<Ksiazka> Ksiazka
		{
			get
			{
				return this._Ksiazka;
			}
			set
			{
				this._Ksiazka.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ksiazka(Ksiazka entity)
		{
			this.SendPropertyChanging();
			entity.Autor = this;
		}
		
		private void detach_Ksiazka(Ksiazka entity)
		{
			this.SendPropertyChanging();
			entity.Autor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Czytelnik")]
	public partial class Czytelnik : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_Czytelnik_Id;
		
		private string _Imie;
		
		private string _Naziwsko;
		
		private string _Email;
		
		private string _Telefon;
		
		private string _Adres;
		
		private EntitySet<Wypozyczenie> _Wypozyczenie;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_Czytelnik_IdChanging(int value);
    partial void OnPk_Czytelnik_IdChanged();
    partial void OnImieChanging(string value);
    partial void OnImieChanged();
    partial void OnNaziwskoChanging(string value);
    partial void OnNaziwskoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    #endregion
		
		public Czytelnik()
		{
			this._Wypozyczenie = new EntitySet<Wypozyczenie>(new Action<Wypozyczenie>(this.attach_Wypozyczenie), new Action<Wypozyczenie>(this.detach_Wypozyczenie));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_Czytelnik_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Pk_Czytelnik_Id
		{
			get
			{
				return this._Pk_Czytelnik_Id;
			}
			set
			{
				if ((this._Pk_Czytelnik_Id != value))
				{
					this.OnPk_Czytelnik_IdChanging(value);
					this.SendPropertyChanging();
					this._Pk_Czytelnik_Id = value;
					this.SendPropertyChanged("Pk_Czytelnik_Id");
					this.OnPk_Czytelnik_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imie", DbType="VarChar(255)")]
		public string Imie
		{
			get
			{
				return this._Imie;
			}
			set
			{
				if ((this._Imie != value))
				{
					this.OnImieChanging(value);
					this.SendPropertyChanging();
					this._Imie = value;
					this.SendPropertyChanged("Imie");
					this.OnImieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Naziwsko", DbType="VarChar(255)")]
		public string Naziwsko
		{
			get
			{
				return this._Naziwsko;
			}
			set
			{
				if ((this._Naziwsko != value))
				{
					this.OnNaziwskoChanging(value);
					this.SendPropertyChanging();
					this._Naziwsko = value;
					this.SendPropertyChanged("Naziwsko");
					this.OnNaziwskoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="VarChar(255)")]
		public string Telefon
		{
			get
			{
				return this._Telefon;
			}
			set
			{
				if ((this._Telefon != value))
				{
					this.OnTelefonChanging(value);
					this.SendPropertyChanging();
					this._Telefon = value;
					this.SendPropertyChanged("Telefon");
					this.OnTelefonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="VarChar(255)")]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Czytelnik_Wypozyczenie", Storage="_Wypozyczenie", ThisKey="Pk_Czytelnik_Id", OtherKey="Fk_Czytelnik_Id")]
		public EntitySet<Wypozyczenie> Wypozyczenie
		{
			get
			{
				return this._Wypozyczenie;
			}
			set
			{
				this._Wypozyczenie.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Wypozyczenie(Wypozyczenie entity)
		{
			this.SendPropertyChanging();
			entity.Czytelnik = this;
		}
		
		private void detach_Wypozyczenie(Wypozyczenie entity)
		{
			this.SendPropertyChanging();
			entity.Czytelnik = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Wypozyczenie")]
	public partial class Wypozyczenie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Pk_Wypozyczenie_Id;
		
		private System.Nullable<int> _Fk_Ksiazka_Id;
		
		private System.Nullable<int> _Fk_Czytelnik_Id;
		
		private string _Data_oddania;
		
		private EntityRef<Czytelnik> _Czytelnik;
		
		private EntityRef<Ksiazka> _Ksiazka;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPk_Wypozyczenie_IdChanging(int value);
    partial void OnPk_Wypozyczenie_IdChanged();
    partial void OnFk_Ksiazka_IdChanging(System.Nullable<int> value);
    partial void OnFk_Ksiazka_IdChanged();
    partial void OnFk_Czytelnik_IdChanging(System.Nullable<int> value);
    partial void OnFk_Czytelnik_IdChanged();
    partial void OnData_oddaniaChanging(string value);
    partial void OnData_oddaniaChanged();
    #endregion
		
		public Wypozyczenie()
		{
			this._Czytelnik = default(EntityRef<Czytelnik>);
			this._Ksiazka = default(EntityRef<Ksiazka>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_Wypozyczenie_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Pk_Wypozyczenie_Id
		{
			get
			{
				return this._Pk_Wypozyczenie_Id;
			}
			set
			{
				if ((this._Pk_Wypozyczenie_Id != value))
				{
					this.OnPk_Wypozyczenie_IdChanging(value);
					this.SendPropertyChanging();
					this._Pk_Wypozyczenie_Id = value;
					this.SendPropertyChanged("Pk_Wypozyczenie_Id");
					this.OnPk_Wypozyczenie_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_Ksiazka_Id", DbType="Int")]
		public System.Nullable<int> Fk_Ksiazka_Id
		{
			get
			{
				return this._Fk_Ksiazka_Id;
			}
			set
			{
				if ((this._Fk_Ksiazka_Id != value))
				{
					if (this._Ksiazka.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFk_Ksiazka_IdChanging(value);
					this.SendPropertyChanging();
					this._Fk_Ksiazka_Id = value;
					this.SendPropertyChanged("Fk_Ksiazka_Id");
					this.OnFk_Ksiazka_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_Czytelnik_Id", DbType="Int")]
		public System.Nullable<int> Fk_Czytelnik_Id
		{
			get
			{
				return this._Fk_Czytelnik_Id;
			}
			set
			{
				if ((this._Fk_Czytelnik_Id != value))
				{
					if (this._Czytelnik.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFk_Czytelnik_IdChanging(value);
					this.SendPropertyChanging();
					this._Fk_Czytelnik_Id = value;
					this.SendPropertyChanged("Fk_Czytelnik_Id");
					this.OnFk_Czytelnik_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Data_oddania", DbType="VarChar(255)")]
		public string Data_oddania
		{
			get
			{
				return this._Data_oddania;
			}
			set
			{
				if ((this._Data_oddania != value))
				{
					this.OnData_oddaniaChanging(value);
					this.SendPropertyChanging();
					this._Data_oddania = value;
					this.SendPropertyChanged("Data_oddania");
					this.OnData_oddaniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Czytelnik_Wypozyczenie", Storage="_Czytelnik", ThisKey="Fk_Czytelnik_Id", OtherKey="Pk_Czytelnik_Id", IsForeignKey=true)]
		public Czytelnik Czytelnik
		{
			get
			{
				return this._Czytelnik.Entity;
			}
			set
			{
				Czytelnik previousValue = this._Czytelnik.Entity;
				if (((previousValue != value) 
							|| (this._Czytelnik.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Czytelnik.Entity = null;
						previousValue.Wypozyczenie.Remove(this);
					}
					this._Czytelnik.Entity = value;
					if ((value != null))
					{
						value.Wypozyczenie.Add(this);
						this._Fk_Czytelnik_Id = value.Pk_Czytelnik_Id;
					}
					else
					{
						this._Fk_Czytelnik_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Czytelnik");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ksiazka_Wypozyczenie", Storage="_Ksiazka", ThisKey="Fk_Ksiazka_Id", OtherKey="Pk_Ksiazka_Id", IsForeignKey=true)]
		public Ksiazka Ksiazka
		{
			get
			{
				return this._Ksiazka.Entity;
			}
			set
			{
				Ksiazka previousValue = this._Ksiazka.Entity;
				if (((previousValue != value) 
							|| (this._Ksiazka.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ksiazka.Entity = null;
						previousValue.Wypozyczenie.Remove(this);
					}
					this._Ksiazka.Entity = value;
					if ((value != null))
					{
						value.Wypozyczenie.Add(this);
						this._Fk_Ksiazka_Id = value.Pk_Ksiazka_Id;
					}
					else
					{
						this._Fk_Ksiazka_Id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Ksiazka");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
